# Generated by Django 4.2.7 on 2023-12-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
